server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /design-kit {
        return 301 $scheme://$http_host/design-kit/;
    }

    location /design-kit/ {
        alias /usr/share/nginx/design-kit/;
        index index.html;
        try_files $uri $uri/ /design-kit/index.html;
    }

    location /pages/ {
        return 301 $scheme://$http_host/design-kit$request_uri;
    }
}
